<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <StartupObject>WslManager.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WslManager.Core/WslManager.Core.csproj" />
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>
